### ISSUE TITLE
Add support for pre-release DuckDB versions (e.g. "pre" feature).

### ISSUE THREAD

**Issue by massung** [wangfenjin/duckdb-rs#121]
The currently released 0.6.1 version of DuckDB has a bug that causes core dumps on Linux using batch insertion (see: https://github.com/duckdb/duckdb/issues/5759).

This bug has been fixed, but hasn't been released yet. It would be great if there was a simple `feature` like `"pre"` or `"dev"` allowing for `libduckdb-sys` to be built against the `main` branch instead of the released version.

**Comment by wangfenjin** [comment]
It's a reasonable requirement, but may not easy to implement as duckdb don't have a pre-release build for us to depends on, which means we may need to checkout the branch or commit-id to build the version we need, this may not that easy.

For now my suggested solution might be use the `buildtime_bindgen` feature, and bring your own duckdb release and header file.

**Comment by wangfenjin** [comment]
Currently our build.rs depends on the `amalgamation`  duckdb.cpp to build, if we don't have that file, it means we need to involve cmake in the build process, which will make the build.rs much more complex than current solution

**Comment by massung** [comment]
Okay. That makes sense. I understand it can complicate the process and that may be undesirable. As an FYI, though, it's not necessary to involve CMake or to "build" anything:

```
git clone https://github.com/duckdb/duckdb
cd duckdb
python3 scripts/amalgamation.py
```

The above will create `src/amalgamation/duckdb.{cpp,hpp}` and runs in a few seconds (but does require Python 3, which may be a reasonable requirement to already be installed). 

I'm fine doing this myself, though. Is there an example of using `buildtime_bindgen` and pointing to those files (or that directory) I can reference?

Thanks!

**Comment by wangfenjin** [comment]
You could refer to the CI process https://github.com/wangfenjin/duckdb-rs/blob/main/.github/workflows/rust.yaml#L37-L60

The idea is download the binary and export the path, and then use the `buildtime_bindgen` feature will do codegen using the exported header file.
For your case is compile the lib and copy the binary to somewhere and export the path

**Comment by wangfenjin** [comment]
Close as it's not in the scope of this project
