### ISSUE TITLE
`version` function

### ISSUE THREAD

**Issue by eitsupi** [wangfenjin/duckdb-rs#124]
It would be nice to have some kind of function to return DuckDB version so that downstream software can easily retrieve the version of DuckDB.

For example, rustsqlite seems to have the `version` function.
https://docs.rs/rusqlite/latest/rusqlite/fn.version.html

**Comment by wangfenjin** [comment]
We could, for now it’s not urgent as we use the same version number as duckdb, and it’s easy for you to query the version by pragmas

https://duckdb.org/docs/sql/pragmas#version
