### ISSUE TITLE
How to compile statically linked executable?

### ISSUE THREAD

**Issue by Dimirolz** [wangfenjin/duckdb-rs#156]
Hello, thanks for an amazing project! It helps a lot.

I'm trying to build a static executable and I already tried everything that I know :)

It's not an issue. I just need a little help. Could you give me a hint in which direction I should dig? Thanks!

**Comment by Dimirolz** [comment]
I'm not even sure how to use `DUCKDB_STATIC`. All my attempts ends with errors from linker like this one:

```
mold: error: undefined symbol: /home/dima/projects/oko/target/release/deps/liblibduckdb_sys-74698eda3a7ee600.rlib(duckdb.o): vtable for __cxxabiv1::__class_type_info
mold: error: undefined symbol: /home/dima/projects/oko/target/release/deps/liblibduckdb_sys-74698eda3a7ee600.rlib(duckdb.o): vtable for __cxxabiv1::__class_type_info
mold: error: undefined symbol: /home/dima/projects/oko/target/release/deps/liblibduckdb_sys-74698eda3a7ee600.rlib(duckdb.o): vtable for __cxxabiv1::__function_type_info
mold: error: undefined symbol: /home/dima/projects/oko/target/release/deps/liblibduckdb_sys-74698eda3a7ee600.rlib(duckdb.o): vtable for __cxxabiv1::__class_type_info
mold: error: undefined symbol: /home/dima/projects/oko/target/release/deps/liblibduckdb_sys-74698eda3a7ee600.rlib(duckdb.o): vtable for __cxxabiv1::__class_type_info
mold: error: undefined symbol: /home/dima/projects/oko/target/release/deps/liblibduckdb_sys-74698eda3a7ee600.rlib(duckdb.o): typeinfo for std::exception
```

**Comment by wangfenjin** [comment]
If you use the bundled feature, by default should be static linking; otherwise you can `export DUCKDB_STATIC=1` to use your own duckdb binary and do static linking.

**Comment by Dimirolz** [comment]
@wangfenjin I tried to use bundled feature and it's not working with the way I'm trying to compile static release.
`RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu` successfully compiles, but on start show me `Segmentation fault`.

I tried to use `cargo build --target=x86_64-unknown-linux-musl --release`  and in this case bundled `libduckdb-sys` cannot compile.  Showing me the error: `error occurred: Failed to find tool. Is `musl-g++` installed?`. I'm not sure if `musl-g++` is even a thing.

I don't waste your time. All this stuff is unrelated to the project.

What is more important, that I cannot statically link using `export DUCKDB_STATIC=1`. I've tried to build duckdb from source and pack it to an ".a" archive. Is this a way? Or what do you mean saying `duckdb binary`?

**Comment by wangfenjin** [comment]
> @wangfenjin I tried to use bundled feature and it's not working with the way I'm trying to compile static release. `RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu` successfully compiles, but on start show me `Segmentation fault`.
> 
> I tried to use `cargo build --target=x86_64-unknown-linux-musl --release` and in this case bundled `libduckdb-sys` cannot compile. Showing me the error: `error occurred: Failed to find tool. Is `musl-g++` installed?`. I'm not sure if `musl-g++` is even a thing.
> 

At least you should enable the `--features="bundled"` , maybe something like `cargo build --release --target x86_64-unknown-linux-gnu --features="bundled"` will work. You can also share your code so I can take a look if it's a open source project.

> I don't waste your time. All this stuff is unrelated to the project.
> 

No worries

> What is more important, that I cannot statically link using `export DUCKDB_STATIC=1`. I've tried to build duckdb from source and pack it to an ".a" archive. Is this a way? Or what do you mean saying `duckdb binary`?

Yes, it is. Then you can export the path like [here](https://github.com/wangfenjin/duckdb-rs/blob/main/.github/workflows/rust.yaml#L100-L102) and `export DUCKDB_STATIC=1`

**Comment by wangfenjin** [comment]
`error occurred: Failed to find tool.` or `Segmentation fault` seems don't related to static linking, you can try clone this repo and run `cargo test --features "modern-full extensions-full"` to verify your local env works fine for compiling c++ code.

**Comment by Dimirolz** [comment]
> error occurred: Failed to find tool. or Segmentation fault seems don't related to static linking, you can try clone this repo and run cargo test --features "modern-full extensions-full" to verify your local env works fine for compiling c++ code.

Thanks, I tried this one and the problem is not in the wrong env. Tests are passing successfully.
`test result: ok. 44 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 15.21s`.

> At least you should enable the --features="bundled" , maybe something like cargo build --release --target x86_64-unknown-linux-gnu --features="bundled" will work. You can also share your code so I can take a look if it's an open source project.

With this command I have an error `error: none of the selected packages contains these features: bundled`. 
But Cargo.toml contains a duckdb package with `bundled` feature already.

Your command at the end will produce a dynamically linked executable that depends on glibc that exists in the system. It will only statically link the duckdb, but not glibc.
What I'm trying to do is to build a fully statically linked executable that contains inside `duckdb` with `glibc`. So I could distribute this binary to different systems, with different `glibc`.

It's working with Go duckdb binary with `go build -ldflags="-extldflags=-static"`. And I'm trying to figure that out for Rust.

To link statically glibc I'm using `RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu`. And it's working well if I don't have duckdb as a dependency. With duckdb (bundled feature) I have in this case `Segmentation fault`.

**Comment by Dimirolz** [comment]
> Yes, it is. Then you can export the path like [here](https://github.com/wangfenjin/duckdb-rs/blob/main/.github/workflows/rust.yaml#L100-L102) and export DUCKDB_STATIC=1. If you enable the bundled feature you don't need to do this.

I did exactly that, export DUCKDB_LIB_DIR, DUCKDB_INCLUDE_DIR, LD_LIBRARY_PATH, and DUCKDB_STATIC=1.
I tried 3 different options for static lib:
1. Compile current duckdb with g++ and archive result to ".a"
2. Get already compiled ".a" from [Golang project](https://github.com/marcboeker/go-duckdb/blob/master/deps/linux_amd64/libduckdb.a)
3. Compile project with bundled feature and get `libduckdb.a` from `libduckdb-sys` cache.

In every of this case I'm getting linker errors (tried different linkers). 

Many lines like this

> mold: error: undefined symbol: /home/dima/projects/oko/target/release/deps/liblibduckdb_sys-74698eda3a7ee600.rlib(duckdb.o): vtable for __cxxabiv1::__class_type_info

**Comment by wangfenjin** [comment]
https://stackoverflow.com/questions/7038258/gcc-4-5-2-linker-gots-problem-while-using-exceptions-c

**Comment by Dimirolz** [comment]
> https://stackoverflow.com/questions/7038258/gcc-4-5-2-linker-gots-problem-while-using-exceptions-c

Yup, this is it. With `export RUSTFLAGS="-C link-arg=-lstdc++"` it successfully statically compiles duckdb from the DUCKDB_LIB_DIR when DUCKDB_STATIC=1.

**Comment by Dimirolz** [comment]
Nope. Can't figure out how to statically compile the whole binary. This problem at the moment is way out of my level.

Thanks for pointing to `lstdc++` . It really helps with compilation time.
