### ISSUE TITLE
Error on 0.8.0

### ISSUE THREAD

**Issue by blackrez** [wangfenjin/duckdb-rs#161]
Hello,

I updated from 0.7.1 to 0.8.0 and I encounter this issue : 
```
Assertion failed: (dynamic_cast<TARGET *>(this)), function Cast, file parse_info.hpp, line 22.
```

It happen when I create a connection 
```
let db = Connection::open_in_memory()?;
```

When I go back to 0.7.1, the code works.

My env is the following : 

- rustc 1.69.0 (84c898d65 2023-04-16) (built from a source tarball)
- cargo 1.69.0 (6e9a83356 2023-04-12)
- MacOS 13.4

**Comment by wangfenjin** [comment]
Create connection? You used the bundled feature or?

**Comment by blackrez** [comment]
Yes I use the bundled feature.

**Comment by wangfenjin** [comment]
You may try cargo clean first.


It shouldn't happen as I'm also using macOS to develop this crate. I'll try to do some local verification, if you can provide a minimal reproducing example it will be better

**Comment by wangfenjin** [comment]
I create a new project locally and verify it works

**Comment by wangfenjin** [comment]
If it still fails on your side you need to provide more information

**Comment by blackrez** [comment]
I confirm `cargo clean` solved the issue. I don't if it is possible when a version is upgraded, that can compile the new version of duckdb.
