### ISSUE TITLE
select from parquet file error

### ISSUE THREAD

**Issue by jaredzhou** [wangfenjin/duckdb-rs#29]
Catalog Error: Table with name /tmp/test.parquet does not exist!

**Comment by wangfenjin** [comment]
seems related to this https://github.com/duckdb/duckdb/issues/2505 you need to enable the parquet extension

**Comment by jaredzhou** [comment]
thanks, that's it. do you have plan to update the arrow crate to  >=6.0.0? that's the main version other crate use.

**Comment by wangfenjin** [comment]
Yes I’ll do it when I got time. Contribution welcomed!

**Comment by aljazerzen** [comment]
@wangfenjin  Is there a way to enable parquet extension when using bundled `libduckdb-sys`?

**Comment by wangfenjin** [comment]
@aljazerzen No we don't. The extension are not distributed with duckdb source, and it's recommend to build the extension as loadable library.

Recommend to try build it yourself and load it, see [examples](https://github.com/duckdb/duckdb/blob/a7493fec044a3d652389039fc942a3d331cf2c16/test/extension/load_extension.test). Or [remote install](https://duckdb.org/docs/extensions/overview) (seems not work for now, there are several issues in duckdb repo related to this)

**Comment by aljazerzen** [comment]
The problem is that I want to include this in a reproducible build for testing PRQL: https://github.com/prql/prql/pull/724

I guess I'll stick to CSV for now.
