### ISSUE TITLE
How to enable parquet (reader)?

### ISSUE THREAD

**Issue by niektemme** [wangfenjin/duckdb-rs#33]
I am a rust newbie, so my apologies if this is a trivial question. I have successfully run the example provided in the examples folder (appender). I am trying to adjust it, by writing / reading a parquet file. The reading capability is actually more important for me at this moment.

I am using the instructions for parquet on. https://duckdb.org/docs/data/parquet
csv import/export using rust and duckdb works. But parquet does not, even though using the cli using the same version on my machine works.

Is there something I need to do to enable parquet? Or is there something else I am doing wrong?

Thanks again for making this!

Using the standard duckdb cli I am able to both export and reat the parquet files. Trying the same queries in rust gives me the following errors. 

1) reading
let mut stmt = db.prepare("SELECT id, count(1) FROM parquet_schema('userdata1.parquet') GROUP BY id")?;

Error: DuckDBFailure(Error { code: Unknown, extended_code: 1 }, Some("Catalog Error: Table Function with name parquet_schema does not exist!\nDid you mean \"duckdb_schemas\"?\nLINE 1: SELECT id, count(1) FROM parquet_schema('userdata1.parquet') GRO...\ 

2) writing
let pragma_t = "COPY (SELECT * FROM test) TO 'result-snappy.parquet' (FORMAT 'parquet');";
db.execute_batch(pragma_t)?;

Error: DuckDBFailure(Error { code: Unknown, extended_code: 1 }, Some("Catalog Error: Copy Function with name parquet does not exist!\nDid you mean \"csv\"?"))

Environment
Mac os X - m1
rustc 1.58.1 (db9d1b20b 2022-01-20)
duckdb  0.3.1

Cargo.toml
[dependencies.duckdb]
version = "0.3.1"
features = ["bundled"]

**Comment by wangfenjin** [comment]
Refer to https://github.com/wangfenjin/duckdb-rs/issues/29 and https://github.com/duckdb/duckdb/issues/2505 , you need to enable build the parquet extension when building duckdb

I think I may need to update the readme

**Comment by niektemme** [comment]
Thanks you for your quick reply. Sorry I missed #29. I will try the with the enabled parquet extension.
