### ISSUE TITLE
uuid::UUID feature - use new DuckDB UUID datatype rather than BLOB

### ISSUE THREAD

**Issue by aarashy** [wangfenjin/duckdb-rs#35]
After duckdb [0.3.0], we should start thinking about using UUID instead of BLOB as the underlying datatype for `uuid::Uuid`. 

A new variant of `Value` seems to be required so that we can stop piggybacking off of Value::Blob. 
```
#[cfg(feature = "uuid")]
impl From<uuid::Uuid> for Value {
    #[inline]
    fn from(id: uuid::Uuid) -> Value {
        Value::Blob(id.as_bytes().to_vec())
    }
}
```

Is it accurate to say that we will require at least 1 PR to the duckdb repo? 
- From what I can see, `/src/appender.rs` makes use of APIs such as `ffi::duckdb_append_blob`, but an API called `ffi::duckdb_append_uuid` doesn't exist yet.

[0.3.0]: https://github.com/duckdb/duckdb/pull/2359

**Comment by wangfenjin** [comment]
Hi @aarashy , yes we may need to make some changes to the duckdb repo, such as the appender you mentioned, and I'm not sure if we need other API like duckdb_bind_uuid() or duckdb_value_uuid() to set/get the value.

Happy to review a PR

**Comment by wangfenjin** [comment]
And another issue I'm think of is, currently we use arrow to query the result, not sure duckdb repo had support return uuid in the arrow result, as uuid is not a predefined type in arrow.

**Comment by wangfenjin** [comment]
> And another issue I'm think of is, currently we use arrow to query the result, not sure duckdb repo had support return uuid in the arrow result, as uuid is not a predefined type in arrow.

I had check the duckdb impl, they return uuid type as string in the result

**Comment by aarashy** [comment]
Thanks for doing some initial work here!

Do you not think that Fixed Size Binary would be the most appropriate arrow representation of a UUID? 
https://arrow.apache.org/docs/cpp/api/datatype.html#_CPPv4N5arrow4Type4type17FIXED_SIZE_BINARYE 

It seems more accurate, since every 128-bit binary is a valid UUID, but not every string is. 

From what I have seen of the upstream duckdb implementation, DuckDB is storing the value as raw bytes, so that should be conducive to this, right?

**Comment by wangfenjin** [comment]
Actually if you check my PR https://github.com/duckdb/duckdb/pull/3136 , current duckdb impl use varchar when convert to arrow. I'm trying to fix that but still have other issue discussing with them.

After that PR merged, we will know how to handle this in our side.
