### ISSUE TITLE
Wasm support?

### ISSUE THREAD

**Issue by maxcountryman** [wangfenjin/duckdb-rs#56]
This doesn't seem to compile within a native Rust Cloudflare Worker. When trying to invoke `wrangler dev` we see this message: `note: rust-lld: error: unable to find library -lduckdb`.

**Comment by wangfenjin** [comment]
I’m not familiar with wasm, duckdb do support that https://github.com/duckdb/duckdb-wasm

**Comment by wangfenjin** [comment]
Close as not related to this repo
