### ISSUE TITLE
Allow bundling of extensions at compilation time

### ISSUE THREAD

**Issue by snth** [wangfenjin/duckdb-rs#91]
Hi,

First of all a huge thank you very much for creating and maintaining this extension! It works wonderfully and I am making extensive use of it in [prql-query](https://github.com/prql/prql-query).

I'm currently loading DuckDB extensions through remote installation, eg `INSTALL parquet; LOAD parquet;` [code example](https://github.com/prql/prql-query/blob/8fec0f8d1ab4856921e6bb1ba2959312f876f4fc/src/backends/duckdb.rs#L128). This works fine but causes a noticeable delay on each invocation.

Discussing this with the DuckDB developers on Discord ([thread](https://discord.com/channels/909674491309850675/922563050173792297/1033016755460780112)) they pointed out that these extensions can be bundled at compile time:

> The various extensions can be bundled by toggling the BUILD_..._EXTENSION in the CMake whereever the shared library is produced:
```
option(BUILD_ICU_EXTENSION "Build the ICU extension." FALSE)
option(BUILD_PARQUET_EXTENSION "Build the Parquet extension." FALSE)
option(BUILD_TPCH_EXTENSION "Build the TPC-H extension." FALSE)
option(BUILD_TPCDS_EXTENSION "Build the TPC-DS extension." FALSE)
option(BUILD_FTS_EXTENSION "Build the FTS extension." FALSE)
option(BUILD_HTTPFS_EXTENSION "Build the HTTP File System extension." FALSE)
option(BUILD_JSON_EXTENSION "Build the JSON extension." FALSE)
option(BUILD_EXCEL_EXTENSION "Build the excel extension." FALSE)
option(BUILD_INET_EXTENSION "Build the inet extension." FALSE)
```

Would it be possible for you to facilitate this somehow?

My guess is that this would have to be done as part of the `libduckdb-sys` build stage somehow but I don't understand enough of this to really attempt a PR for this myself.

**Comment by wangfenjin** [comment]
related to #66

**Comment by snth** [comment]
Thanks. I've commented there.

**Comment by wangfenjin** [comment]
For the bundled version in duckdb-rs, we used the [released amalgamation code ](https://github.com/duckdb/duckdb/releases/download/v0.5.1/libduckdb-src.zip) to build duckdb, which makes it easy to build as it's a single cpp file.

But seems the source code of extension is not included in amalgamation version.😭

**Comment by wangfenjin** [comment]
Currently the easiest solution is to download the release lib from duckdb or build the lib by yourself, and then export the path so duckdb-rs can find it, something like this:

```shell
export DUCKDB_LIB_DIR=/Users/wangfenjin/duckdb
export DUCKDB_INCLUDE_DIR=/Users/wangfenjin/duckdb
export LD_LIBRARY_PATH=/Users/wangfenjin/duckdb:$LD_LIBRARY_PATH
```

You'd better make the downloaded lib is same version with duckdb-rs, otherwise the behavior maybe undefined.


And do NOT enable `bundled` feature in your Cargo.toml:

```rust
duckdb = { version = "0.5.1", features = ["modern-full"] }
```

**Comment by wangfenjin** [comment]
Also try reuse the connection, so that you don't need to install the extension every time.

**Comment by wangfenjin** [comment]
https://discord.com/channels/909674491309850675/922563050173792297/1033449293551521882

Seems not a small change if we want to host the extension code

**Comment by wangfenjin** [comment]
> Also try reuse the connection, so that you don't need to install the extension every time.

@snth I may suggest you to try this way first, should be minimal change.

Or try the released lib from duckdb repo, but need extra setup

**Comment by snth** [comment]
I would rather not go the lib route because I'm trying to create a simple, standalone binary for people to use and don't want to have to ship other libraries with it. That python build script that mytherin posted on Discord didn't look that bad. I'll see if I can work with that. I just haven't had time to take a proper look at this yet.

**Comment by gd87429** [comment]
I'd also be interested in bundling `httpfs` at compile time. Same as @snth, aiming for standalone binary.

**Comment by gd87429** [comment]
> Also try reuse the connection, so that you don't need to install the extension every time.

@wangfenjin Since none of duckdb is `Send + Sync`, is there a way to reuse the connection (to not install `httpfs` every time) in a system that spins a lot of threads in parallel?

**Comment by wangfenjin** [comment]
Is clone works?

https://github.com/wangfenjin/duckdb-rs/blob/e636b3b0caa5f2de06a717da42c7fe719bb9812c/src/lib.rs#L516

**Comment by gd87429** [comment]
@wangfenjin, yep that's it, `try_clone()` did the trick. Thank you.

By the way, looks like installing an extension might be a one-time deal (at least in my own testing setup). If I restart the program, all I have to do is `LOAD` it into a connection every time. So, might be a valid strategy to install once during program startup, and then just check for it (at least until there's a reliable way to bundle extensions during compile time).

Thank you for this library btw 💪
