### ISSUE TITLE
Re-export dependencies (in particular arrow) to avoid version incompatibilties in client crates

### ISSUE THREAD

**Issue by snth** [wangfenjin/duckdb-rs#92]
Hi,

The Rust Arrow crate is used in many projects through the Rust data ecosystem (duckdb-rs, DataFusion, Polars, connectorx, ...). They also rapidly cycle through major version numbers (currently v25 and I think they were on 19 when I started a few months ago). This makes it extremely difficult if not impossible to find common version numbers to use in any client crate if you want to use more than one of these projects in one crate.

The only way around this that I have found so far is to use a re-exported version from the place where it is used. DataFusion does this for example here: https://github.com/apache/arrow-datafusion/blob/572c20e904b48ea4819210b983d41b1b08c23b46/datafusion/core/src/lib.rs#L232

Please can you add the same top-level re-export to duckdb-rs? It has to be the `arrow` crate at the top-level because I use a number of items from it.

This is probably a one line change and I'm happy to submit a PR for it if you like.

**Comment by wangfenjin** [comment]
Thanks @snth , it’ll be great if you can submit an PR for this 🙏
