### ISSUE TITLE
Baffled by problems building libduckdb-sys with Dockerfile

### ISSUE THREAD

**Issue by richb-hanover** [wangfenjin/duckdb-rs#95]
I am also working on the `prql` project, and trying to create a Dockerfile to encapulate all the machinery in a reproducible Docker container. I encounter a problem with an error while compiling libduckdb-sys. 

Specifically, I'm working with the [prql-query repo](https://github.com/prql/prql-query). I can run `cargo build` natively without problem. But when I attempt to use `docker build -t pq .` on the repo, I get the error reported in this Issue: [error: failed to run custom build command for libduckdb-sys v0.5.1](https://github.com/prql/prql-query/issues/9) 

Here's an excerpt showing the error message - The original report lists all the details. Any ideas about how to troubleshoot this? Many thanks.

```
# error from "docker build -t pq ." ...
...
#12 470.9 The following warnings were emitted during compilation:
#12 470.9
#12 470.9 warning: c++: fatal error: Killed signal terminated program cc1plus
#12 470.9 warning: compilation terminated.
#12 470.9
#12 470.9 error: failed to run custom build command for `libduckdb-sys v0.5.1`
#12 470.9
#12 470.9 Caused by:
#12 471.0   process didn't exit successfully: `/app/target/release/build/libduckdb-sys-dd2866ecae070e6b/build-script-build` (exit status: 1)
...
```

**Comment by wangfenjin** [comment]
Let’s discuss in prql issue

**Comment by richb-hanover** [comment]
Yes - using Docker Desktop to increase Resources -> Memory solved the problem. See https://github.com/prql/prql-query/issues/9 Thanks.
